package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AvailiabilityBlockAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailiabilityBlockAllPropertiesEquals(AvailiabilityBlock expected, AvailiabilityBlock actual) {
        assertAvailiabilityBlockAutoGeneratedPropertiesEquals(expected, actual);
        assertAvailiabilityBlockAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailiabilityBlockAllUpdatablePropertiesEquals(AvailiabilityBlock expected, AvailiabilityBlock actual) {
        assertAvailiabilityBlockUpdatableFieldsEquals(expected, actual);
        assertAvailiabilityBlockUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailiabilityBlockAutoGeneratedPropertiesEquals(AvailiabilityBlock expected, AvailiabilityBlock actual) {
        assertThat(expected)
            .as("Verify AvailiabilityBlock auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailiabilityBlockUpdatableFieldsEquals(AvailiabilityBlock expected, AvailiabilityBlock actual) {
        assertThat(expected)
            .as("Verify AvailiabilityBlock relevant properties")
            .satisfies(e -> assertThat(e.getStartDateTime()).as("check startDateTime").isEqualTo(actual.getStartDateTime()))
            .satisfies(e -> assertThat(e.getEndDateTime()).as("check endDateTime").isEqualTo(actual.getEndDateTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailiabilityBlockUpdatableRelationshipsEquals(AvailiabilityBlock expected, AvailiabilityBlock actual) {
        assertThat(expected)
            .as("Verify AvailiabilityBlock relationships")
            .satisfies(e -> assertThat(e.getUser()).as("check user").isEqualTo(actual.getUser()));
    }
}
