package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FindTimeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFindTimeAllPropertiesEquals(FindTime expected, FindTime actual) {
        assertFindTimeAutoGeneratedPropertiesEquals(expected, actual);
        assertFindTimeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFindTimeAllUpdatablePropertiesEquals(FindTime expected, FindTime actual) {
        assertFindTimeUpdatableFieldsEquals(expected, actual);
        assertFindTimeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFindTimeAutoGeneratedPropertiesEquals(FindTime expected, FindTime actual) {
        assertThat(expected)
            .as("Verify FindTime auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFindTimeUpdatableFieldsEquals(FindTime expected, FindTime actual) {
        assertThat(expected)
            .as("Verify FindTime relevant properties")
            .satisfies(e -> assertThat(e.getRequestStart()).as("check requestStart").isEqualTo(actual.getRequestStart()))
            .satisfies(e -> assertThat(e.getRequestEnd()).as("check requestEnd").isEqualTo(actual.getRequestEnd()))
            .satisfies(e -> assertThat(e.getLength()).as("check length").isEqualTo(actual.getLength()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFindTimeUpdatableRelationshipsEquals(FindTime expected, FindTime actual) {
        assertThat(expected)
            .as("Verify FindTime relationships")
            .satisfies(e -> assertThat(e.getRequester()).as("check requester").isEqualTo(actual.getRequester()))
            .satisfies(e -> assertThat(e.getParticipants()).as("check participants").isEqualTo(actual.getParticipants()))
            .satisfies(e -> assertThat(e.getSuggestions()).as("check suggestions").isEqualTo(actual.getSuggestions()));
    }
}
