package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FriendshipAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendshipAllPropertiesEquals(Friendship expected, Friendship actual) {
        assertFriendshipAutoGeneratedPropertiesEquals(expected, actual);
        assertFriendshipAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendshipAllUpdatablePropertiesEquals(Friendship expected, Friendship actual) {
        assertFriendshipUpdatableFieldsEquals(expected, actual);
        assertFriendshipUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendshipAutoGeneratedPropertiesEquals(Friendship expected, Friendship actual) {
        assertThat(expected)
            .as("Verify Friendship auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendshipUpdatableFieldsEquals(Friendship expected, Friendship actual) {
        assertThat(expected)
            .as("Verify Friendship relevant properties")
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendshipUpdatableRelationshipsEquals(Friendship expected, Friendship actual) {
        assertThat(expected)
            .as("Verify Friendship relationships")
            .satisfies(e -> assertThat(e.getUser()).as("check user").isEqualTo(actual.getUser()))
            .satisfies(e -> assertThat(e.getFriend()).as("check friend").isEqualTo(actual.getFriend()));
    }
}
