package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ScheduleRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduleRequestAllPropertiesEquals(ScheduleRequest expected, ScheduleRequest actual) {
        assertScheduleRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertScheduleRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduleRequestAllUpdatablePropertiesEquals(ScheduleRequest expected, ScheduleRequest actual) {
        assertScheduleRequestUpdatableFieldsEquals(expected, actual);
        assertScheduleRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduleRequestAutoGeneratedPropertiesEquals(ScheduleRequest expected, ScheduleRequest actual) {
        assertThat(expected)
            .as("Verify ScheduleRequest auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduleRequestUpdatableFieldsEquals(ScheduleRequest expected, ScheduleRequest actual) {
        assertThat(expected)
            .as("Verify ScheduleRequest relevant properties")
            .satisfies(e -> assertThat(e.getStartDate()).as("check startDate").isEqualTo(actual.getStartDate()))
            .satisfies(e -> assertThat(e.getEndDate()).as("check endDate").isEqualTo(actual.getEndDate()))
            .satisfies(e ->
                assertThat(e.getScheduleDescription()).as("check scheduleDescription").isEqualTo(actual.getScheduleDescription())
            )
            .satisfies(e -> assertThat(e.getIntensity()).as("check intensity").isEqualTo(actual.getIntensity()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduleRequestUpdatableRelationshipsEquals(ScheduleRequest expected, ScheduleRequest actual) {
        assertThat(expected)
            .as("Verify ScheduleRequest relationships")
            .satisfies(e -> assertThat(e.getUser()).as("check user").isEqualTo(actual.getUser()));
    }
}
