package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SuggestionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuggestionAllPropertiesEquals(Suggestion expected, Suggestion actual) {
        assertSuggestionAutoGeneratedPropertiesEquals(expected, actual);
        assertSuggestionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuggestionAllUpdatablePropertiesEquals(Suggestion expected, Suggestion actual) {
        assertSuggestionUpdatableFieldsEquals(expected, actual);
        assertSuggestionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuggestionAutoGeneratedPropertiesEquals(Suggestion expected, Suggestion actual) {
        assertThat(expected)
            .as("Verify Suggestion auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuggestionUpdatableFieldsEquals(Suggestion expected, Suggestion actual) {
        assertThat(expected)
            .as("Verify Suggestion relevant properties")
            .satisfies(e -> assertThat(e.getSuggestedStart()).as("check suggestedStart").isEqualTo(actual.getSuggestedStart()))
            .satisfies(e -> assertThat(e.getSuggestedEnd()).as("check suggestedEnd").isEqualTo(actual.getSuggestedEnd()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuggestionUpdatableRelationshipsEquals(Suggestion expected, Suggestion actual) {
        assertThat(expected)
            .as("Verify Suggestion relationships")
            .satisfies(e -> assertThat(e.getFindTimes()).as("check findTimes").isEqualTo(actual.getFindTimes()));
    }
}
